package org.objectstyle.cayenne.testdo.mt.auto;

import java.util.List;

import org.objectstyle.cayenne.PersistentObject;
import org.objectstyle.cayenne.testdo.mt.ClientMtTable2;

/**
 * Class _ClientMtTable1 was generated by Cayenne. It is probably a good idea to avoid
 * changing this class manually, since it will be overwritten next time code is
 * regenerated. If you need to make any customizations, put them in a subclass.
 */
public class _ClientMtTable1 extends PersistentObject {

    public static final String GLOBAL_ATTRIBUTE1_PROPERTY = "globalAttribute1";
    public static final String SERVER_ATTRIBUTE1_PROPERTY = "serverAttribute1";
    public static final String TABLE2ARRAY_PROPERTY = "table2Array";

    protected String globalAttribute1;
    protected String serverAttribute1;
    protected List table2Array;

    public void setGlobalAttribute1(String globalAttribute1) {
        willWrite("globalAttribute1", getGlobalAttribute1(), globalAttribute1);
        this.globalAttribute1 = globalAttribute1;
    }
    public String getGlobalAttribute1() {
        willRead("globalAttribute1");
        return globalAttribute1;
    }
    
    
    public void setServerAttribute1(String serverAttribute1) {
        willWrite("serverAttribute1", getServerAttribute1(), serverAttribute1);
        this.serverAttribute1 = serverAttribute1;
    }
    public String getServerAttribute1() {
        willRead("serverAttribute1");
        return serverAttribute1;
    }
    
    
    /**
     * Sets 'table2Array' lazy list. In most cases this method shouldn't be used directly as
     * the list is initialized by Cayenne.
     */
	public void setTable2Array(List list) {
        this.table2Array = list;
    }
    public void addToTable2Array(ClientMtTable2 obj) {
        willRead("table2Array");
        // TODO:
    }
    public void removeFromTable2Array(ClientMtTable2 obj) {
        willRead("table2Array");
        // TODO:
    }
    public List getTable2Array() {
        willRead("table2Array");
        return table2Array;
    }
    
}
