package org.objectstyle.cayenne.testdo.mt.auto;

import org.objectstyle.cayenne.PersistentObject;
import org.objectstyle.cayenne.testdo.mt.ClientMtTable1;

/** Class _ClientMtTable2 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually,
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, put them in a subclass. 
  */
public class _ClientMtTable2 extends PersistentObject {

    public static final String GLOBAL_ATTRIBUTE_PROPERTY = "globalAttribute";
    public static final String TABLE1_PROPERTY = "table1";

    protected String globalAttribute;
    protected ClientMtTable1 table1;

    public void setGlobalAttribute(String globalAttribute) {
        willWrite("globalAttribute", getGlobalAttribute(), globalAttribute);
        this.globalAttribute = globalAttribute;
    }
    public String getGlobalAttribute() {
        willRead("globalAttribute");
        return globalAttribute;
    }
    
    
    public void setTable1(ClientMtTable1 table1) {
        willWrite("table1", getTable1(), table1);
        this.table1 = table1;
    }

    public ClientMtTable1 getTable1() {
        willRead("table1");
        return table1;
    } 
    
}
