package org.objectstyle.cayenne.testdo.mt.auto;

import org.objectstyle.cayenne.PersistentObject;
import org.objectstyle.cayenne.ValueHolder;
import org.objectstyle.cayenne.testdo.mt.ClientMtTable1;

/**
 * Class _ClientMtTable2 was generated by Cayenne. It is probably a good idea to avoid
 * changing this class manually, since it will be overwritten next time code is
 * regenerated. If you need to make any customizations, put them in a subclass.
 */
public class _ClientMtTable2 extends PersistentObject {

    public static final String GLOBAL_ATTRIBUTE_PROPERTY = "globalAttribute";
    public static final String TABLE1_PROPERTY = "table1";

    protected String globalAttribute;
    protected ValueHolder table1Holder;

    public void setGlobalAttribute(String globalAttribute) {
        willWrite("globalAttribute", getGlobalAttribute(), globalAttribute);
        this.globalAttribute = globalAttribute;
    }
    public String getGlobalAttribute() {
        willRead("globalAttribute");
        return globalAttribute;
    }
    
    
    /**
     * Sets ValueHolder of 'table1' property. Cayenne uses this setter to inject a ValueHolder.
     */
    public void setTable1Holder(ValueHolder holder) {
        this.table1Holder = holder;
    }

    public void setTable1(ClientMtTable1 table1) {
        willWrite("table1", getTable1(), table1);
        this.table1Holder.setValue(ClientMtTable1.class, table1);
    }

    public ClientMtTable1 getTable1() {
        willRead("table1");
        return (ClientMtTable1) table1Holder.getValue(ClientMtTable1.class);
    } 
    
}
