package org.objectstyle.cayenne.testdo.mt.auto;

import org.objectstyle.cayenne.PersistentObject;

/** Class _ClientMtTable1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _ClientMtTable1 extends PersistentObject {

    public static final String GLOBAL_ATTRIBUTE1_PROPERTY = "globalAttribute1";
    public static final String SERVER_ATTRIBUTE1_PROPERTY = "serverAttribute1";

    public static final String TABLE1_ID_PK_COLUMN = "TABLE1_ID";

    protected String globalAttribute1;
    protected String serverAttribute1;

    public void setGlobalAttribute1(String globalAttribute1) {
        willWrite("globalAttribute1", getGlobalAttribute1(), globalAttribute1);
        this.globalAttribute1 = globalAttribute1;
    }
    public String getGlobalAttribute1() {
        willRead("globalAttribute1");
        return globalAttribute1;
    }
    
    
    public void setServerAttribute1(String serverAttribute1) {
        willWrite("serverAttribute1", getServerAttribute1(), serverAttribute1);
        this.serverAttribute1 = serverAttribute1;
    }
    public String getServerAttribute1() {
        willRead("serverAttribute1");
        return serverAttribute1;
    }
    
    
}
