package org.objectstyle.cayenne.examples.ejbfacade.model.auto;

import java.util.List;

/** Class _Auction was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Auction extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String CLOSING_TIME_PROPERTY = "closingTime";
    public static final String CURRENT_PRICE_PROPERTY = "currentPrice";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String MIN_INCREMENT_PROPERTY = "minIncrement";
    public static final String NAME_PROPERTY = "name";
    public static final String START_PRICE_PROPERTY = "startPrice";
    public static final String START_TIME_PROPERTY = "startTime";
    public static final String PAINTINGS_PROPERTY = "paintings";

    public static final String AUCTION_ID_PK_COLUMN = "AUCTION_ID";

    public void setClosingTime(java.util.Date closingTime) {
        writeProperty("closingTime", closingTime);
    }
    public java.util.Date getClosingTime() {
        return (java.util.Date)readProperty("closingTime");
    }
    
    
    public void setCurrentPrice(Float currentPrice) {
        writeProperty("currentPrice", currentPrice);
    }
    public Float getCurrentPrice() {
        return (Float)readProperty("currentPrice");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setMinIncrement(Float minIncrement) {
        writeProperty("minIncrement", minIncrement);
    }
    public Float getMinIncrement() {
        return (Float)readProperty("minIncrement");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setStartPrice(Float startPrice) {
        writeProperty("startPrice", startPrice);
    }
    public Float getStartPrice() {
        return (Float)readProperty("startPrice");
    }
    
    
    public void setStartTime(java.util.Date startTime) {
        writeProperty("startTime", startTime);
    }
    public java.util.Date getStartTime() {
        return (java.util.Date)readProperty("startTime");
    }
    
    
    public void addToPaintings(org.objectstyle.cayenne.examples.ejbfacade.model.Painting obj) {
        addToManyTarget("paintings", obj, true);
    }
    public void removeFromPaintings(org.objectstyle.cayenne.examples.ejbfacade.model.Painting obj) {
        removeToManyTarget("paintings", obj, true);
    }
    public List getPaintings() {
        return (List)readProperty("paintings");
    }
    
    
}
