package org.objectstyle.cayenne.examples.ejbfacade.model.auto;

import java.util.List;

/** Class _Gallery was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Gallery extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String GALLERY_NAME_PROPERTY = "galleryName";
    public static final String PAINTINGS_PROPERTY = "paintings";

    public static final String GALLERY_ID_PK_COLUMN = "GALLERY_ID";

    public void setGalleryName(String galleryName) {
        writeProperty("galleryName", galleryName);
    }
    public String getGalleryName() {
        return (String)readProperty("galleryName");
    }
    
    
    public void addToPaintings(org.objectstyle.cayenne.examples.ejbfacade.model.Painting obj) {
        addToManyTarget("paintings", obj, true);
    }
    public void removeFromPaintings(org.objectstyle.cayenne.examples.ejbfacade.model.Painting obj) {
        removeToManyTarget("paintings", obj, true);
    }
    public List getPaintings() {
        return (List)readProperty("paintings");
    }
    
    
}
