/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.objectstyle.cayenne.wocompat.parser;

public interface ParserConstants {

  int EOF = 0;
  int INT = 5;
  int FLOAT = 6;
  int STRING = 14;
  int QUOTED_STRING = 27;

  int DEFAULT = 0;
  int WithinQuotedString = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<INT>",
    "<FLOAT>",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "<STRING>",
    "\"\\\"\"",
    "<token of kind 16>",
    "\"\\\\\\\\\"",
    "\"\\\\a\"",
    "\"\\\\b\"",
    "\"\\\\t\"",
    "\"\\\\n\"",
    "\"\\\\v\"",
    "\"\\\\f\"",
    "\"\\\\\\\"\"",
    "<token of kind 25>",
    "<token of kind 26>",
    "\"\\\"\"",
  };

}
