/* Generated By:JJTree: Do not edit this line. src/cayenne/java/org/objectstyle/cayenne/util/parser/ExpressionParserTreeConstants.java */

package org.objectstyle.cayenne.util.parser;

public interface ExpressionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTADDITIVEEXPRESSION = 2;
  public int JJTMULTIPLICATIVEEXPRESSION = 3;
  public int JJTUNARYEXPRESSION = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTINTEGER = 6;


  public String[] jjtNodeName = {
    "start",
    "expression",
    "additiveExpression",
    "multiplicativeExpression",
    "unaryExpression",
    "identifier",
    "integer",
  };
}
