/* Generated By:JJTree: Do not edit this line. src/cayenne/java/org/objectstyle/cayenne/util/parser/PlistParserTreeConstants.java */

package org.objectstyle.cayenne.util.parser;

public interface PlistParserTreeConstants
{
  public int JJTOBJECT = 0;
  public int JJTLEAF = 1;
  public int JJTDICTIONARY = 2;
  public int JJTARRAY = 3;


  public String[] jjtNodeName = {
    "object",
    "leaf",
    "dictionary",
    "array",
  };
}
