package org.objectstyle.art.oneway;

import java.util.List;
import org.objectstyle.cayenne.*;

/** Class _Artist was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Artist extends org.objectstyle.cayenne.CayenneDataObject {

    public void setArtistName(String artistName) {
        writeProperty("artistName", artistName);
    }
    public String getArtistName() {
        return (String)readProperty("artistName");
    }
    
    
    public void setDateOfBirth(java.sql.Time dateOfBirth) {
        writeProperty("dateOfBirth", dateOfBirth);
    }
    public java.sql.Time getDateOfBirth() {
        return (java.sql.Time)readProperty("dateOfBirth");
    }
    
    
}
