package org.objectstyle.art.oneway;

import java.util.List;
import org.objectstyle.cayenne.*;

/** Class _Gallery was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Gallery extends org.objectstyle.cayenne.CayenneDataObject {

    public void setGalleryName(String galleryName) {
        writeProperty("galleryName", galleryName);
    }
    public String getGalleryName() {
        return (String)readProperty("galleryName");
    }
    
    
}
