package org.objectstyle.art.auto;

/** Class _DeleteRuleTest3 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _DeleteRuleTest3 extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String TO_DELETE_RULE_TEST2_PROPERTY = "toDeleteRuleTest2";

    public static final String DELETE_RULE_TEST_3_ID_PK_COLUMN = "DELETE_RULE_TEST_3_ID";

    public void setToDeleteRuleTest2(org.objectstyle.art.DeleteRuleTest2 toDeleteRuleTest2) {
        setToOneTarget("toDeleteRuleTest2", toDeleteRuleTest2, true);
    }

    public org.objectstyle.art.DeleteRuleTest2 getToDeleteRuleTest2() {
        return (org.objectstyle.art.DeleteRuleTest2)readProperty("toDeleteRuleTest2");
    } 
    
    
}
