package test;

import java.util.List;
import org.objectstyle.cayenne.*;

/** Class _Artist was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Artist extends CayenneDataObject {

    public void setDateOfBirth(java.sql.Time dateOfBirth) {
        writeProperty("dateOfBirth", dateOfBirth);
    }
    public java.sql.Time getDateOfBirth() {
        return (java.sql.Time)readProperty("dateOfBirth");
    }
    
    
    public void setArtistName(java.lang.String artistName) {
        writeProperty("artistName", artistName);
    }
    public java.lang.String getArtistName() {
        return (java.lang.String)readProperty("artistName");
    }
    
    
    public void addToPaintingArray(test.Painting obj) {
        addToManyTarget("paintingArray", obj, true);
    }
    public void removeFromPaintingArray(test.Painting obj) {
        removeToManyTarget("paintingArray", obj, true);
    }
    public List getPaintingArray() {
        return (List)readProperty("paintingArray");
    }
    
    
}
