/* Generated By:JJTree: Do not edit this line. ASTAnd.java */

package org.objectstyle.cayenne.exp.parser;

import org.objectstyle.cayenne.exp.Expression;

class ASTAnd extends SimpleNode {

    public ASTAnd(int id) {
        super(id);
    }

    public ASTAnd(ExpressionParser p, int id) {
        super(p, id);
    }

    public int getType() {
        return Expression.AND;
    }

    public void jjtClose() {
        super.jjtClose();
        flattenTree();
    }

    protected String getExpressionOperator(int index) {
        return "and";
    }
}
