/* Generated By:JJTree: Do not edit this line. ASTBetween.java */

package org.objectstyle.cayenne.exp.parser;

import org.objectstyle.cayenne.exp.Expression;

class ASTBetween extends SimpleNode {
    protected boolean negating;

    public ASTBetween(int id) {
        super(id);
    }

    public ASTBetween(ExpressionParser p, int id) {
        super(p, id);
    }

    protected String getExpressionOperator(int index) {
        return (index == 2) ? "and" : (negating) ? "not between" : "between";
    }

    public int getType() {
        return (negating) ? Expression.NOT_BETWEEN : Expression.BETWEEN;
    }

    boolean isNegating() {
        return negating;
    }

    void setNegating(boolean negating) {
        this.negating = negating;
    }
}
