/* Generated By:JJTree: Do not edit this line. ASTEqual.java */

package org.objectstyle.cayenne.exp.parser;

import org.objectstyle.cayenne.exp.Expression;

class ASTEqual extends SimpleNode {
    protected boolean negating;

    public ASTEqual(int id) {
        super(id);
    }

    public ASTEqual(ExpressionParser p, int id) {
        super(p, id);
    }

    protected String getExpressionOperator(int index) {
        return (negating) ? "!=" : "=";
    }

    public int getType() {
        return (negating) ? Expression.NOT_EQUAL_TO : Expression.EQUAL_TO;
    }

    boolean isNegating() {
        return negating;
    }

    void setNegating(boolean negating) {
        this.negating = negating;
    }
}
