/* Generated By:JJTree: Do not edit this line. ASTGreater.java */

package org.objectstyle.cayenne.exp.parser;

import org.objectstyle.cayenne.exp.Expression;

class ASTGreater extends SimpleNode {
    public ASTGreater(int id) {
        super(id);
    }

    public ASTGreater(ExpressionParser p, int id) {
        super(p, id);
    }

    protected String getExpressionOperator(int index) {
        return ">";
    }

    public int getType() {
        return Expression.GREATER_THAN;
    }
}
