/* Generated By:JJTree: Do not edit this line. ASTIn.java */

package org.objectstyle.cayenne.exp.parser;

import org.objectstyle.cayenne.exp.Expression;

class ASTIn extends SimpleNode {
    protected boolean negating;

    public ASTIn(int id) {
        super(id);
    }

    public ASTIn(ExpressionParser p, int id) {
        super(p, id);
    }

    protected String getExpressionOperator(int index) {
        return (negating) ? "not in" : "in";
    }

    public int getType() {
        return (negating) ? Expression.NOT_IN : Expression.IN;
    }

    boolean isNegating() {
        return negating;
    }

    void setNegating(boolean negating) {
        this.negating = negating;
    }
}
