/* Generated By:JJTree: Do not edit this line. ASTLess.java */

package org.objectstyle.cayenne.exp.parser;

import org.objectstyle.cayenne.exp.Expression;

class ASTLess extends SimpleNode {
    public ASTLess(int id) {
        super(id);
    }

    public ASTLess(ExpressionParser p, int id) {
        super(p, id);
    }

    protected String getExpressionOperator(int index) {
        return "<";
    }

    public int getType() {
        return Expression.LESS_THAN;
    }
}
