/* Generated By:JJTree: Do not edit this line. ASTNamedParameter.java */

package org.objectstyle.cayenne.exp.parser;

import org.objectstyle.cayenne.exp.ExpressionException;
import org.objectstyle.cayenne.exp.ExpressionParameter;

class ASTNamedParameter extends ASTScalar {

    public ASTNamedParameter(int id) {
        super(id);
    }

    public ASTNamedParameter(ExpressionParser p, int id) {
        super(p, id);
    }

    void setValue(Object value) {
        if (value == null) {
            throw new ExpressionException("Null Parameter value");
        }

        String name = value.toString().trim();
        if (name.length() == 0) {
            throw new ExpressionException("Empty Parameter value");
        }

        super.setValue(new ExpressionParameter(name));
    }
}
