/* Generated By:JJTree: Do not edit this line. ASTNot.java */

package org.objectstyle.cayenne.exp.parser;

import org.objectstyle.cayenne.exp.Expression;

class ASTNot extends SimpleNode {
    public ASTNot(int id) {
        super(id);
    }

    public ASTNot(ExpressionParser p, int id) {
        super(p, id);
    }

    public int getType() {
        return Expression.NOT;
    }

    protected void toStringBuffer(StringBuffer buf) {
        buf.append("not ");
        super.toStringBuffer(buf);
    }
}
