/* Generated By:JJTree: Do not edit this line. ASTNot.java */

package org.objectstyle.cayenne.exp.parser;

import java.io.PrintWriter;

import org.objectstyle.cayenne.exp.Expression;

class ASTNot extends SimpleNode {
    public ASTNot(int id) {
        super(id);
    }

    public ASTNot(ExpressionParser p, int id) {
        super(p, id);
    }

    public int getType() {
        return Expression.NOT;
    }

    public void encodeAsString(PrintWriter pw) {
        pw.print("not ");
        super.encodeAsString(pw);
    }
}
