/* Generated By:JJTree: Do not edit this line. ASTScalar.java */

package org.objectstyle.cayenne.exp.parser;

import java.io.PrintWriter;

class ASTScalar extends SimpleNode {
    public ASTScalar(int id) {
        super(id);
    }

    public ASTScalar(ExpressionParser p, int id) {
        super(p, id);
    }

    public void encode(PrintWriter pw) {
        boolean quote = value instanceof String;

        if (quote) {
            pw.print('\"');
        }
        encodeString(pw, String.valueOf(value));
        if (quote) {
            pw.print('\"');
        }
    }
}
