/* Generated By:JJTree: Do not edit this line. src/cayenne/java/org/objectstyle/cayenne/exp/parser/ExpressionParserTreeConstants.java */

package org.objectstyle.cayenne.exp.parser;

public interface ExpressionParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTOR = 1;
  public int JJTAND = 2;
  public int JJTNOT = 3;
  public int JJTEQUAL = 4;
  public int JJTLESSOREQUAL = 5;
  public int JJTLESS = 6;
  public int JJTGREATER = 7;
  public int JJTGREATEROREQUAL = 8;
  public int JJTLIKE = 9;
  public int JJTIN = 10;
  public int JJTBETWEEN = 11;
  public int JJTLIST = 12;
  public int JJTSCALAR = 13;
  public int JJTNAMEDPARAMETER = 14;
  public int JJTOBJPATH = 15;
  public int JJTDBPATH = 16;


  public String[] jjtNodeName = {
    "void",
    "Or",
    "And",
    "Not",
    "Equal",
    "LessOrEqual",
    "Less",
    "Greater",
    "GreaterOrEqual",
    "Like",
    "In",
    "Between",
    "List",
    "Scalar",
    "NamedParameter",
    "ObjPath",
    "DbPath",
  };
}
