CREATE TABLE AUTO_PK_SUPPORT (
       TABLE_NAME           CHAR(100) NOT NULL,
       NEXT_ID              INTEGER NOT NULL,
       PRIMARY KEY (TABLE_NAME)
)
CREATE TABLE ARTIST (
       ARTIST_ID            INTEGER NOT NULL,
       ARTIST_NAME          VARCHAR(255) NOT NULL,
       DATE_OF_BIRTH        DATE NULL,
       PRIMARY KEY (ARTIST_ID)
)
CREATE TABLE GALLERY (
       GALLERY_ID           INTEGER NOT NULL,
       GALLERY_NAME         VARCHAR(100) NOT NULL,
       PRIMARY KEY (GALLERY_ID)
)

CREATE TABLE EXHIBIT (
       EXHIBIT_ID           INTEGER NOT NULL,
       GALLERY_ID           INTEGER NOT NULL,
       OPENING_DATE         DATE NOT NULL,
       CLOSING_DATE         DATE NOT NULL,
       PRIMARY KEY (EXHIBIT_ID)
)

CREATE TABLE ARTIST_EXHIBIT (
       ARTIST_ID            INTEGER NOT NULL,
       EXHIBIT_ID           INTEGER NOT NULL,
       PRIMARY KEY (ARTIST_ID, EXHIBIT_ID)
)

CREATE TABLE PAINTING (
       PAINTING_ID          INTEGER NOT NULL,
       GALLERY_ID           INTEGER NULL,
       ARTIST_ID            INTEGER NULL,
       ESTIMATED_PRICE      NUMERIC NULL,
       PAINTING_TITLE       VARCHAR(255) NOT NULL,
       PRIMARY KEY (PAINTING_ID)
)
CREATE TABLE PAINTING_INFO (
       PAINTING_ID          INTEGER NOT NULL,
       TEXT_REVIEW          VARCHAR(255) NULL,
       IMAGE_BLOB           BLOB NULL
)


