package org.objectstyle.cayenne.examples.aggregate.auto;

/** Class _PaintingStats was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _PaintingStats extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String MAX_PRICE_PROPERTY = "maxPrice";
    public static final String MIN_PRICE_PROPERTY = "minPrice";
    public static final String PAINTINGS_COUNT_PROPERTY = "paintingsCount";
    public static final String ARTIST_PROPERTY = "artist";

    public static final String ARTIST_ID_PK_COLUMN = "ARTIST_ID";

    public void setMaxPrice(java.math.BigDecimal maxPrice) {
        writeProperty("maxPrice", maxPrice);
    }
    public java.math.BigDecimal getMaxPrice() {
        return (java.math.BigDecimal)readProperty("maxPrice");
    }
    
    
    public void setMinPrice(java.math.BigDecimal minPrice) {
        writeProperty("minPrice", minPrice);
    }
    public java.math.BigDecimal getMinPrice() {
        return (java.math.BigDecimal)readProperty("minPrice");
    }
    
    
    public void setPaintingsCount(Integer paintingsCount) {
        writeProperty("paintingsCount", paintingsCount);
    }
    public Integer getPaintingsCount() {
        return (Integer)readProperty("paintingsCount");
    }
    
    
    public void setArtist(org.objectstyle.cayenne.examples.aggregate.Artist artist) {
        setToOneTarget("artist", artist, true);
    }
    
    public org.objectstyle.cayenne.examples.aggregate.Artist getArtist() {
        return (org.objectstyle.cayenne.examples.aggregate.Artist)readProperty("artist");
    } 
    
    
}
